server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  data:
    mongodb:
      database: ${DATABASE:localhost}
      password: ${PASSWORD:password}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:8050}
      username: ${USERNAME:test}
credential:
  skype:
    login: ${SKYPE_USER_NAME:}
    password: ${SKYPE_PASSWORD:}
  skype2:
    login: ${SKYPE2_USER_NAME:}
    password: ${SKYPE2_PASSWORD:}
  telegram:
    login: ${TELEGRAM_BOT_NAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
  ai:
    token: ${AI_TOKEN:token}
bot:
  config:
    datatype: ${DATATYPE:mongo}
    silentPeriod: ${SILENTPERIOD:10}
    threadCount: ${THREAD_COUNT:10}
    queueSize: ${QUEUE_SIZE:100}
proxy:
  config:
    host: ${PROXY_HOST:}
    port: ${PROXY_PORT:}
    user: ${PROXY_USER:}
    pass: ${PROXY_PASS:}
instaprovider:
  url: ${INSTAPROVIDER_URL:https://instaprovider.now.sh}
banner:
  charset: