server:
    address: 0.0.0.0
    port: ${PORT}

spring:
  data:
    mongodb:
      database: ${DATABASE}
      password: ${PASSWORD}
      host: ${HOST}
      port: ${PORT}
      username: ${USERNAME}