server:
    address: 0.0.0.0
    port: ${PORT}

spring:
  data:
    mongodb:
      database: ${DATABASE}
      password: ${PASSWORD}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${USERNAME}
credential:
  skype:
    login: ${SKYPE_USER_NAME}
    password: ${SKYPE_PASSWORD}
  skype2:
    login: ${SKYPE2_USER_NAME}
    password: ${SKYPE2_PASSWORD}
  telegram:
    login: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}
  ai:
    token: ${AI_TOKEN}